name: Roblox Luau Framework Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install Python
      run: sudo apt install python3
    
    - name: double-sync
      run: git pull origin main

    - name: translate test
      run: python3 utils/translate-rblx.py
