name: Translate Luau to Roblox framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install Python
      run: sudo apt install python3

    - name: translate
      run: python3 utils/translate-rblx.py

    - name: update identity name
      run: git config user.name "cardboard-bot"
    
    - name: update identity email
      run: git config user.email "runner@fv-az891-754.3qows1xflhlezoxdqozyuy3a1h.bx.internal.cloudapp.net"
    
    - name: commit
      run: git commit -a -m "[translations] auto-translate code to Roblox luau"

    - name: push to translation remote
      run: git push -u origin roblox-translation